require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/inter_team_trades', :no_transaction, type: :request do
  let(:round) { create :round, :current }
  let(:fpl_team1) { create :fpl_team }
  let(:fpl_team2) { create :fpl_team, league: fpl_team1.league }
  let(:fpl_team_list1) { create :fpl_team_list, fpl_team: fpl_team1, round: round }
  let(:fpl_team_list2) { create :fpl_team_list, fpl_team: fpl_team2, round: round }

  let(:position) { create :position, :forward }
  let(:player1) { create :player, position: position }
  let(:player2) { create :player, position: position }

  let!(:list_position1) { create :list_position, player: player1, fpl_team_list: fpl_team_list1 }
  let!(:list_position2) { create :list_position, player: player2, fpl_team_list: fpl_team_list2 }

  let(:inter_team_trade_group) do
    create(
      :inter_team_trade_group,
      out_fpl_team_list: fpl_team_list1,
      in_fpl_team_list: fpl_team_list2,
    )
  end

  let!(:inter_team_trade) do
    create(
      :inter_team_trade,
      inter_team_trade_group: inter_team_trade_group,
      out_player: player1,
      in_player: player2,
    )
  end

  before { api.authenticate(fpl_team_list1.owner) }

  describe 'DELETE /destroy' do
    it 'destroys the inter team trade' do
      expect do
        api.delete api_fpl_team_list_inter_team_trade_url(fpl_team_list1, inter_team_trade)
      end
      .to change(InterTeamTrade, :count).from(1).to(0)
      .and change(InterTeamTradeGroup, :count).from(1).to(0)

      expect(api.response).to have_http_status(:success)

      expect(api.data['in_trade_groups']).to be_empty
      expect(api.data['out_trade_groups']).to be_empty
    end

    it 'returns a 422 if there is an error' do
      fpl_team1.update(owner: create(:user))

      expect do
        api.delete api_fpl_team_list_inter_team_trade_url(fpl_team_list1, inter_team_trade)
      end
      .to not_change { InterTeamTrade.count }
      .and not_change { InterTeamTradeGroup.count }

      expect(response).to have_http_status(:unprocessable_entity)

      expect(api.errors).to contain_exactly(
        a_hash_including('detail' => 'You are not authorised to perform this action', 'source' => 'base'),
      )
    end
  end
end
